[package]
name = "RateMyVcc"
version = "0.1.0"
edition = "2024"

[lib]
name = "RateMyVcc"
crate-type = ["cdylib"]

[dependencies]
csv = "1.3.1"
neon = "1.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
